export  const dummySpaceXMissions = [
    {
      id: 1,
      name: 'Mission 1',
      date: '2023-01-10',
      rocketUsed: 'Falcon 5',
      success: true,
      manufacturer: 'SpaceX',
    },
    {
      id: 2,
      name: 'Mission 2',
      date: '2023-02-15',
      rocketUsed: 'Falcon Heavy',
      success: false,
      manufacturer: 'SpaceX',
    },
    {
      id: 3,
      name: 'Mission 3',
      date: '2023-03-20',
      rocketUsed: 'Falcon 9',
      success: true,
      manufacturer: 'SpaceX',
    },
    {
      id: 4,
      name: 'Mission 4',
      date: '2023-04-25',
      rocketUsed: 'Falcon 9',
      success: true,
      manufacturer: 'SpaceX',
    },
    {
      id: 5,
      name: 'Mission 5',
      date: '2023-05-30',
      rocketUsed: 'Falcon Heavy',
      success: false,
      manufacturer: 'SpaceX',
    },
    {
      id: 6,
      name: 'Mission 6',
      date: '2023-06-10',
      rocketUsed: 'Falcon 10',
      success: true,
      manufacturer: 'SpaceX',
    },
    {
      id: 7,
      name: 'Mission 7',
      date: '2023-07-15',
      rocketUsed: 'Falcon 11',
      success: true,
      manufacturer: 'SpaceX',
    },
    {
      id: 8,
      name: 'Mission 8',
      date: '2023-08-20',
      rocketUsed: 'Falcon Heavy',
      success: false,
      manufacturer: 'SpaceX',
    },
    {
      id: 9,
      name: 'Mission 9',
      date: '2023-09-25',
      rocketUsed: 'Falcon 12',
      success: true,
      manufacturer: 'SpaceX',
    },
    {
      id: 10,
      name: 'Mission 10',
      date: '2023-10-05',
      rocketUsed: 'Falcon 13',
      success: true,
      manufacturer: 'SpaceX',
    },
    {
      id: 11,
      name: 'Mission 11',
      date: '2023-11-15',
      rocketUsed: 'Falcon Heavy',
      success: false,
      manufacturer: 'SpaceX',
    },
    {
      id: 12,
      name: 'Mission 12',
      date: '2023-12-20',
      rocketUsed: 'Falcon 15',
      success: true,
      manufacturer: 'SpaceX',
    },
  ];
  

  